spring.application.name=Civil-service-competition

server.port=8081
logging.level.root=ERROR
logging.level.com.AGETIC.Civil_service_competition=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO



# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/civil_service_competition
spring.datasource.username=postgres
spring.datasource.password=Postgre2002.

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

